# 2024-03-07 13:20
# 1.24.5
name: act-build

on:
  workflow_dispatch:

env:
  TAG_NAME:      "wget"
  TAG_VERSION:   "v1.24.5"
  TAG_BUILD:     "-b"
  TAG_REF:       "0000000"
  PROG_NAME:     "wget"
  PROG_VERSION:  "v1.24.5"
  VERSION:       "1.24.5"
  SH_FILE_NAME:  "-1-24-5"
  DRAFT:         false

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: deep-soft/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get install -y mingw-w64 mingw-w64-tools mingw-w64-i686-dev gcc
          sudo apt-get install -y make m4 pkg-config automake gettext

      - name: Build wget 64-bit
        run: |
          x86_64-w64-mingw32-gcc --version
          bash ./build${{ env.SH_FILE_NAME }}.sh

      - name: Build wget 32-bit
        run: |
          i686-w64-mingw32-gcc --version
          bash ./build-x86${{ env.SH_FILE_NAME }}.sh

      - name: Publish
        continue-on-error: true
        uses: deep-soft/action-gh-release@v2.1
        with:
          tag_name: ${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}
          files: |
            build-wget-webfolder.io/install/wget-gnutls/wget-gnutls-x64.exe
            build-wget-webfolder.io/install/wget-openssl/wget-openssl-x64.exe
            build-wget-webfolder-x86.io/install/wget-gnutls/wget-gnutls-x86.exe
            build-wget-webfolder-x86.io/install/wget-openssl/wget-openssl-x86.exe
